# Generated by Django 4.2.4 on 2023-08-11 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_friends_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("ACCEPTED", "accepted"),
                            ("DELETED", "deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "from_friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_friend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_friend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
