# Generated by Django 4.2.4 on 2023-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_groupchatroom_admin_user_groupchatroom_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchatroom",
            name="image",
            field=models.ImageField(
                default="C:\\Users\\Shree\\Videos\\DjangoWebSocket\\chatnotiboard\\media\\profile_pictures\\download.png",
                upload_to="group_image",
            ),
        ),
    ]
