# Generated by Django 4.2.4 on 2023-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_groupchatroom_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchatroom",
            name="image",
            field=models.ImageField(
                default="C:\\Users\\Shree\\Videos\\DjangoWebSocket\\chatnotiboard\\core\\static\\images\\download.jpeg",
                upload_to="group_image",
            ),
        ),
    ]
