# Generated by Django 4.2.4 on 2023-08-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_groupchatroom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessagesmodel",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
